name: Build web image and push to ECR

on:
  push:
    branches:
      - 'staging'
      - 'main'
    paths:
      - 'web/**'

concurrency:
  group: build_docker_image_web

jobs:
  build:
    name: Web build
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Log in to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Push to staging if on staging branch
    - name: Build, tag, and push to ECR
      if: github.ref == 'refs/heads/staging'
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: web-staging
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd web
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile.prod .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    # Push to prod if on main branch
    - name: Build, tag, and push to ECR
      if: github.ref == 'refs/heads/main'
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: web-prod
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd web
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile.prod .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Log out of ECR
      if: always()
      run: docker logout ${{ steps.login-ecr.registry }}
