name: Prod infra apply

on:
  push:
    branches:
      - 'main'
    paths:
      - 'iac/**'

concurrency:
  group: terraform_iac_prod

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Change to IaC directory
      run: cd ./iac

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      run: terraform fmt -check

    - name: Terraform init
      run: terraform init

    - name: Terraform apply
      run: terraform apply -auto-approve -input=false -var environment="prod"